# Generated by Django 5.2.9 on 2026-05-05 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_flashsale_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created',
            field=models.DateTimeField(auto_created=True, default='2026'),
        ),
    ]
