# Generated by Django 5.2.9 on 2025-12-30 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_options_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.CharField(default=False, max_length=10),
        ),
    ]
